### ISSUE TITLE
Ignore Binary Files from Diff

### ISSUE THREAD

**Issue by demisx** [gitlabhq/gitlabhq#6916]
Hi. Is there a way to exclude binary files, or files matching certain extensions, from GitLab visual Diff in the merge requests? Currently, a merge request with one HTML file and a few PDF files shows: 

```
Warning! This is a large diff.
To preserve performance the diff is not shown. Please, download the diff as plain diff or email patch instead.
```

I, and probably most others, care less about visually diffing binary files in MRs. As long as they show up as "different"--it's good enough. However, I don't want them to block diff generation of plain text files.

Thank you.

**Comment by davidagee** [comment]
+1 for @Schepp's suggestion.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by clns** [comment]
I'm sorry but I don't see how this issue has been fixed in newer versions of GitLab.

I just upgraded to GitLab 8.2 from 8.1, I have a `.gitattributes` file in the root of the repository to exclude `*.map` files from the diff (`*.map  -diff`). It all works fine from the cli using `git diff`, but I still see the files in GitLab when viewing a diff.

**Comment by Razer6** [comment]
GitLab does not support  `.gitattributes` right now. @stanhu You are working on `libgit2` to support `.gitattributes`. Is this something which can be added easiliy?

**Comment by alexander-schranz** [comment]
how to ignore specific files just from the diff when `.gitattributes` is not supported? this issue seems not to be fixed.

**Comment by matto1990** [comment]
Any response on this issue? I agree that I don't think it's fixed.

**Comment by pingers** [comment]
We're treating generated CSS as binary in our project (via .gitattributes) and Gitlab is consistently timing out to the point where users can't create merge requests. Would love to see .gitattributes respected in Gitlab. Cheers!

**Comment by alexander-schranz** [comment]
@pingers @matto1990 seems like they move the .gitattributes support to 8.5 release https://gitlab.com/gitlab-org/gitlab-ce/issues/2315. i hope they get it to work on 8.5.

**Comment by pingers** [comment]
Thanks for the info - not long now - cheers!

**Comment by matto1990** [comment]
Yep, reading that thread again it seems to suggest that merge drivers will also be supported. It seems like for Gitlab to support this, libgit2/libgit2#3597 and then libgit2/libgit2#3564 need to be merged in.

**Comment by alexander-schranz** [comment]
anybody got luck with the new 8.5 version? For me it still shows the diff.

![bildschirmfoto 2016-02-22 um 16 13 51](https://cloud.githubusercontent.com/assets/1698337/13222337/d8120fd4-d97f-11e5-8e85-1384bbd167d8.png)

**Comment by matto1990** [comment]
I think (not a developer on any of these projects) this won't be fixed until:

1. libgit2/libgit2#3564 is merged in
2. [Rugged](https://github.com/libgit2/rugged) is updated to include the new code
3. Gitlab updates their Rugged dependency

**Comment by stanhu** [comment]
Also, custom merge drivers are not the same as custom diff drivers. I think the latter could be implemented separately by ignoring binary files based on `.gitattributes`.

**Comment by grouchal** [comment]
I also do not think this issue is fixed - why is it closed?

**Comment by jnbt** [comment]
This sadly is really an issue for our team. Working with Unity 3D always leads to large MRs as assets are saved as "text"-files. This is very useful as it allows merging the changes in these files as Unity also ships with merging tools. 
BUT sadly we often cannot use GitLab's MR feature as the diff is always to large to show. I think @Schepp solution would really be great.

**Comment by MadsBogeskov** [comment]
Our team has the same problem as @jnbt

**Comment by matto1990** [comment]
There's an issue opened on Gitlab and I've opened a merge request to fix it. I just need to find some time to fix some tests and it should be good to go.

https://gitlab.com/gitlab-org/gitlab-ce/issues/2315

**Comment by jnbt** [comment]
@matto1990 I've seen your work. A big thanks as your MR is accepted now. So we can expect this feature for 8.8

**Comment by matto1990** [comment]
@jnbt No problem. It should be in 8.8 I assume

**Comment by networm** [comment]
Add following content to 'info/attributes' file on GitLab sever's repository:

*.asset -diff
*.unity -diff
*.prefab -diff

I have tested on GitLab 8.5.7 and 8.8.1.

**Comment by sparrowDom** [comment]
@networm can you please elaborate how to achieve this? I have created an `attributes` file in the server's repository inside `info` folder with the suggested contents, but the *.prefab and *.unity files still show in the Merge Requests' diff. 

I am doing this on Gitlab.com and not on self hosted server.

**Comment by johnou** [comment]
@sparrowDom we have a ```.gitattributes``` in the root of our git repo (not the info folder) which seems to work okay.

```text
*.asset binary
*.meta binary
```

**Comment by networm** [comment]
You need ssh to your server to add info/attributes to bare repository
manually. I think you could not do that since you didn't have ssh in
GitLab.com.
This is just a workaround for GitLab didn't recognize .gitattributes bug.
You could report a bug to GitLab.

Domen Grabec <notifications@github.com>于2017年9月19日 周二18:35写道：

**Comment by networm** [comment]
Sorry for unconfirmed comment.

I have tested .gitattributes on self hosted GitLab 9.5.5 which is the
latest version by now.
And I also test it on GitLab.com which is 10.0.0-rc4-ee by now.
This bug has been fixed on both sides.

So you could just put your ignore pattern in .gitattributes file in the
root of repository.

Johno Crawford <notifications@github.com>于2017年9月19日 周二18:45写道：

**Comment by sparrowDom** [comment]
<img width="962" alt="screenshot 2017-09-19 13 06 43" src="https://user-images.githubusercontent.com/579910/30589626-7789579a-9d3b-11e7-8a69-b9b059cd18fd.png">

@johnou thanks for the suggestion. Though somehow files marked as binary still show in the Merge Request diff. See `.meta` file in the attached screenshot.

**Comment by networm** [comment]
I think you should test it after .gitattributes merged in master branch.
Because the enabled .gitattributes didn't contain meta binary.

Domen Grabec <notifications@github.com>于2017年9月19日 周二19:08写道：

**Comment by sparrowDom** [comment]
@networm changing the .gitattributes on master solved the issue. Thank you
