### ISSUE TITLE
Pre-receive hook fails with gitlab-omnibus if /var/opt is a symlink

### ISSUE THREAD

**Issue by FooBarWidget** [gitlabhq/gitlabhq#8521]
We have a rather unique server setup where /var/opt is symlinked to /home/system/var_opt. The reason why we do this is because the server is partially encrypted. The base system is unencrypted, and most of the actual data lives in the encrypted partition. /opt and /var/opt are thus symlinked to directories within the encrypted partition.

However this causes gitlab-omnibus's pre-receive hook to fail. In the pre-receive hook, `repo_path` evaluates to `/home/system/var_opt/gitlab/git-data/repositories/...` -- the expanded version of the path. This causes `GitlabAccess.new(repo_path, key_id, refs).exec` to fail. Whatever command it executes, it outputs:

    GitLab: No such project

We solved this problem locally by adding the following line to the pre-release hook which fixes up the path:

    # In /opt/gitlab/embedded/service/gitlab-shell/hooks/pre-receive:
    repo_path.sub!("/home/system/var_opt/", "/var/opt/")

**Comment by David-Turbert** [comment]
Maybe you have the same probleme than me, try edit
```
/etc/gitlab/gitlab.rb 
```
and change 
```
git_data_dir "/home/system/var_opt/"
```
after you can launch
```
sudo gitlab-ctl reconfigure
```

**Comment by d-snp** [comment]
Hi, that solved it for us. This issue can be closed now :+1:

**Comment by FooBarWidget** [comment]
I don't think the issue can be closed. While our problem has been solved, I
believe the underlying problem is that Gitlab doesn't handle symlinks
correctly. We shouldn't have to use the suggested config option.

**Comment by vanjor** [comment]
agree with @FooBarWidget too.
For me both /var/log/gitlab and /var/opt/gitlab are symlinks. and encounter the same error. 
and just update
"# In /opt/gitlab/embedded/service/gitlab-shell/hooks/pre-receive:
repo_path.sub!("/home/system/var_opt/", "/var/opt/")"
"sudo gitlab-ctl reconfigure"
the error still occurred.
Thus force to not using symlinks, which make it very inflexible.

**Comment by maxlazio** [comment]
`git_data_dir` exists for just such needs, when you need to move your data to a non standard location. Making sure that symlinks are correctly followed is not a simple task and would require number of changes like creating wrapper scripts or changing every call to filesystem to check for the realpath. It is unlikely that such change will happen.

**Comment by Razer6** [comment]
For the omnibus package please head over to the omnibus repository: https://gitlab.com/gitlab-org/omnibus-gitlab
