### ISSUE TITLE
"Please complete your profile with email address"

### ISSUE THREAD

**Issue by mikew** [gitlabhq/gitlabhq#8575]
When a new user signs into Gitlab via LDAP they are forced onto the profile settings page with this message, however in a rather annoying fashion the email field is readonly for LDAP users, thus there is no way for the user to get out of this loop.

Even removing the `readonly` property via the browser's inspector doesn't help.

And when trying to delete said user, gitlab returns a 500 error:

```
Started DELETE "/admin/users/katie" for 127.0.0.1 at 2015-01-14 18:34:11 -0400
Processing by Admin::UsersController#destroy as HTML
  Parameters: {"authenticity_token"=>"2uTCBXTvxiEo1gbMV3apUNc2QalRhpIsbm6FK2DFbnc=", "id"=>"katie"}
Completed 500 Internal Server Error in 46ms

NoMethodError (undefined method `name' for nil:NilClass):
  app/controllers/admin/users_controller.rb:92:in `destroy'
```

**Comment by maartenoortwijn** [comment]
I actually got in after removing the readonly attribute. After entering my email address and saving I received an email to confirm my account.

**Comment by mvala** [comment]
I have same problem. Is there any solution to this? I logged in as admin and update email on that user and everything is fine now. But it think it is not solution.

**Comment by mikeobrien** [comment]
Only seems to happen with the first user to login. I deleted that user from GitLab and tried again and it hasn't happened since.

**Comment by sean-clayton** [comment]
I'm still having this issue. Removing the readonly attribute did nothing. I even used an admin account and edited the profile and that works temporarily. After logging in, the temp email still persists. Anyone who logs in through LDAP (have tried with 3 new accounts) can't do anything at all. Very annoying, to say the least :(

**Comment by mvala** [comment]
My issue was fixed when i filled
bind_dn: 'uid=admin,cn=users,cn=accounts,dc=xxx,dc=xx'
password : 'somevalue'

**Comment by sean-clayton** [comment]
I figured out a solution to my issue. I don't know if all of this is necessary, but I know the LDAP user config is. What we did was set `allow_username_or_email_login` to `true`, disabled "Allow users to register any application to use GitLab as an OAuth provider" in the admin settings, and made our LDAP user config have a field "mail" set. Any user without having "mail" set would run into the aforementioned issue. Hope this helped someone!

**Comment by zhmocean** [comment]
Email seems to be reset when LDAP login. I'm not having this issue at "7.5.3", but it's happens at "7.11.4" "7.12.2" and "7.13.1" with the same env config. Any changes for login?

**Comment by zhmocean** [comment]
After some test I found the problem that "mail" be reset by LDAP login happens at 7.10 version  first, I think it might be a new login feature led to this problem, so I can only use the 7.9 version first before find the solution

**Comment by kozmaz87** [comment]
I have the same problem on 7.13.5
Removing and readding the same user does NOT fix the problem. LDAP integration in this form makes the system unusable.

**Comment by Razer6** [comment]
This is due to ruby2.2. GitLab requires a ruby 2.1

**Comment by psg9999** [comment]
We have having this same issue with an ldap backed authentication installation of CE, and running ruby 2.1, at least reported by the admin site as 2.1.6.  Adding and dropping users does not fix this issue for us.


GitLab 7.14.3

GitLab Shell 2.6.5

GitLab API v3

Ruby 2.1.6p336

Rails 4.1.11

**Comment by jschueller** [comment]
same here, with gitlab 8.0.1 on jessie, ruby 2.1

was it that commit ?
https://github.com/gitlabhq/gitlabhq/commit/b2e4664cc78d61ec058e81f37cdff11636b02967

**Comment by zhmocean** [comment]
I found a temporary solution for this issue:
change generate_temporarily_email method in service/gitlab-rails/lib/gitlab/o_auth/auth_hash.rb for generating formal email for LDAP user

**Comment by zhmocean** [comment]
I found a temporary solution for this issue:
change generate_temporarily_email method in lib/gitlab/o_auth/auth_hash.rb for generating formal email for LDAP user.

Can we add a switch for it?

**Comment by schaffino** [comment]
Can we re-open this issue? I'm having the same problem on 

GitLab 8.1.1
GitLab Shell 2.6.5
GitLab API v3
Ruby 2.1.7p400
Rails 4.1.12

The issue seems to be with ldap accounts that don't have an associated email. Even if i modify the emails as admin it gets overwritten when the user logs in.

Regards

Josh

**Comment by sean-clayton** [comment]
@schaffino I've had an open ticket addressing the lack of an associated email that _really_ is required, but not documented since Jul 22. #9471

**Comment by axilleas** [comment]
Opening until documented.

**Comment by fhimpe** [comment]
I really think this needs more than an update to the documentation. It is extremely annoying having to add e-mail addresses in the LDAP directory just for GitLab. GitLab really needs the option to set the e-mail address locally in its own database when it's not set in LDAP.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
