### ISSUE TITLE
Can't log in; "No authentication methods configured."

### ISSUE THREAD

**Issue by pduersteler** [gitlabhq/gitlabhq#8589]
I just updated from 6.9.2 to 7.7.0 (branch 7-7-stable). It does not matter what I put into `config/gitlab.yml`, I always see "No authentication methods configured." when browsing to `users/sign_in`.

Currently, I've set `signin_enabled: true`, which in my understanding should display the form. I checked, and `signin_enabled?` is `nil` in the view instead of the value given from the gitlab config file.

**Comment by axilleas** [comment]
Fixed in master https://gitlab.com/gitlab-org/gitlab-ce/commit/5e0497758276660989cda53f86346954b53a17ad

**Comment by eafzali** [comment]
I've updated my gitlab omnibus to 7.7.1 and having the same issue. could you solve that @pduersteler? I have also added this line to my gitlab.rb file but there's still no sign in form in `users/sign-in`:
```
gitlab_rails['gitlab_signin_enabled'] = true
```

**Comment by lukasbisdorf** [comment]
Same here @eafzali. 
Updated today, the update went well as usual. After updating the option "sign_up" was enabled in the admin backend, unchecked this, and logged out to look if this takes any effect, it took - but now I am unable to sign in. 

GitLab is installed via Omnibus.  

Any chances to get around this ? Or do I have to roll back?

**Comment by lukasbisdorf** [comment]
Workaround if you only see the register form: 
1. Create a user with another email adress.
2. Confirm the link --> you will get logged in.
3. Go to server via ssh
4. do the following: 

    gitlab-ctl console
    u = User.find_by_email("yourregistered@email.com")
    u.admin = true
    u.save

5. Refresh the browser. Go to the admin panel an reenable sing_in!.
6. Take an other Browser windows to check if sing_in works.
7. Log in with your Admin account and delete the temp. user.

**Comment by eafzali** [comment]
My problem solved using https://gitlab.com/gitlab-org/omnibus-gitlab/issues/413#note_779794

**Comment by maxlazio** [comment]
@lukasbisdorf Did you do `gitlab-ctl stop` before running the reconfigure?

/cc @eafzali

**Comment by lukasbisdorf** [comment]
I tried both.
When gitlab was stopped, the reconfigure step ran into an ruby exception. Don't know if I can reproduce this. 
When gitlab is running, the reconfigure runs without a problem, but the changes in the ``gitlab.rb`` did not take any effect. Especially setting the sign_in and sign_up vars.

**Comment by Wiggy123** [comment]
I have the same problem since upgrading to 7.7.0 (Omnibus). Just upgraded to 7.7.1, which includes the fix from axilleas, still the same problem.

@lukasbisdorf: your workaround didn't work for me either, since I don't even get a register form (with signup being enabled).

eafzali suggested `gitlab-rake db:migrate`, didn't help either (`gitlab-rake db:migrate:status`seems to indicate all migrations were completed successfully).

Any ideas what else I can try, besides rolling back (which I don't want to do, because custom post-receive hooks work in 7.7.1 and that's something I'd like to use)?

**Comment by Wiggy123** [comment]
For me, this really ugly workaround helps until further investigation:
I changed `embedded/service/gitlab-rails/app/views/devise/shared/_signin_box.html.haml`, that's where the `signin_enabled` variable is checked (which for whatever reason is always `false` in my environment, even though it is set to `true` in gitlab.rb and gitlab.yml):

At the bottom, change the code to something like this:

    //    - elsif signin_enabled?
       - else
          = render 'devise/sessions/new_base'
    //    - else
    //      %div
    //        No authentication methods configured.

Now the signin is always enabled (if you use LDAP, you need to change it in the first branch). Drawback: you can't disable it anymore. As I said, ugly hack, not recommended at all, but works for now for me.

**Comment by krisdigitx** [comment]
i diabled signin hoping that all the repositories will be available to anyone via gitlab, however its giving the same error
"
No authentication methods configured.
"

any ideas?

**Comment by nickckaye** [comment]
Problem solved via:
```
sudo gitlab-rake db:migrate
```

**Comment by brice92** [comment]
Same here, this solved this problem : 

sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production

**Comment by maxlazio** [comment]
@lukasbisdorf  the reason why I asked was that if GitLab was stopped migration would fail and you wouldn't get the required changes. 

For everyone else:
Always make sure that all migrations ran on upgrade if somethign is not working, use `db:migrate:status`.

@krisdigitx You disabled `signin` so it is expected for no one to be able to sign in.

**Comment by Wiggy123** [comment]
@maxlazio As I wrote, I did `gitlab-rake db:migrate`, and `gitlab-rake db:migrate:status` returns "up" for all entries, so everything seems to have migrated successfully.
Still doesn't work...

**Comment by robertd** [comment]
FYI... in v7.7.2 default option for `signup_enabled` is `false`. In current master it's `true`. [L68](https://github.com/gitlabhq/gitlabhq/blob/master/config/gitlab.yml.example#L68)

**Comment by speedlight** [comment]
+1 to gitlab-rake db:migrate

**Comment by natedavis** [comment]
+1 to sudo gitlab-rake db:migrate

**Comment by ychoucha** [comment]
same problem here, and now way to make it work !!
help

**Comment by aligtp** [comment]
no ways above worked for me !!!

**Comment by windcoo** [comment]
+1 to sudo gitlab-rake db:migrate

**Comment by rwx------** [comment]
You can use the Rails console to reenable your sign-in.

```
sudo gitlab-rails console
s = ApplicationSetting.find_by(signin_enabled: false)
s.signin_enabled = true
s.save
```
This will modify the rails settings directly.

from: 
https://stackoverflow.com/questions/40073037/how-to-recover-from-no-authentication-methods-configured-on-login-page
